#!/bin/bash 

# If an additional q-var needs to be added
./addQvar
mv q.save q.save_old
mv q.save_temp q.save


# Make sure the input file has an NQT = 505 
# Also make sure initial OUTVAR is set to 0 

varnames=( 'REV' 'RETC' 'FONSET1' 'FONSET2' 'FONSET3' 'FONSET' 'DNU' 'SIJSQ' 'DNUY2' )
varlen=${#varnames[@]} 
varnum=( 0 3 4 5 6 7 8 9 10 11 )  # This array has an extra entry to start the sed at 0

for (( i=0; i<${varlen}; i++ )) ; do
	sed "s/OUTVAR = ${varnum[i]}/OUTVAR = ${varnum[i+1]}/g" < naca.3.inp > temp
        mv temp naca.3.inp
	overrun naca.3 > output.out 
	echo ${varnames[i]} > finp
	# if run on Hilbert
	# echo '11' >> finp 
	extractvar < finp
done







